# Generated by Django 4.1.5 on 2023-01-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_code",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
