# Generated by Django 4.1.5 on 2023-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRefreshToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.TextField()),
                ("jti", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("blacklisted_at", models.DateTimeField(blank=True, null=True)),
                ("blacklisted", models.BooleanField(default=False)),
                ("ip_address", models.CharField(blank=True, max_length=39)),
            ],
        ),
    ]
